version: "3.9"

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: server
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
