version: "3.8"
services:
  go-app:
    image: go-app:latest
    ports:
      - "80:8080"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1 # Update one replica at a time
        delay: 10s # Brief delay between updates
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3
