version: "3.8"

services:
  traefik:
    image: traefik:v2.9
    command:
      # Enable both HTTP and HTTPS entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Enable Docker provider so that Traefik auto-configures itself based on container labels
      - "--providers.docker=true"
      # Enable the Traefik dashboard (for production, secure this!)
      - "--api.insecure=true"
      # ACME (Let's Encrypt) configuration for automatic certificate generation and renewal
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80" # Expose HTTP
      - "443:443" # Expose HTTPS
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/letsencrypt:/letsencrypt"
    networks:
      - web

  go-app:
    image: go-app:latest
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    # Remove direct port publishing, since Traefik will route to this container over the "web" network
    networks:
      - web
    labels:
      - "traefik.enable=true"
      # Create a router for the service by matching the domain api.postprove.com (case sensitive)
      - "traefik.http.routers.go-app.rule=Host(`api.postprove.com`)"
      # Specify which Traefik entrypoints the router connects to
      - "traefik.http.routers.go-app.entrypoints=web,websecure"
      # Use the ACME resolver for TLS (this will only trigger if you access via HTTPS)
      - "traefik.http.routers.go-app.tls.certresolver=myresolver"
      # Tell Traefik which port inside the container to route traffic to (this is the internal port your app is listening on)
      - "traefik.http.services.go-app.loadbalancer.server.port=8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3

networks:
  web:
    external: true
