api:
  dashboard: true
  insecure: true  # Don't use this in production!

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    swarmMode: true
    exposedByDefault: false
    network: traefik-net

log:
  level: INFO

# Optional: Add access logs
accessLog: {}
