version: "3.9"
services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.goapp.rule=Host(`api.postprove.com`)"
        - "traefik.http.services.goapp.loadbalancer.server.port=8080"
        - "traefik.http.routers.goapp.entrypoints=web"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
