name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set USER environment variable
        run: echo "USER=$(whoami)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          tags: go-app:latest  # Local image tag
          load: true # Load the image into the local Docker daemon
          platform: linux/arm64

      - name: Deploy to Docker Swarm
        run: |
          # Add commands to deploy to your Docker Swarm
          # For example:
          # docker stack deploy --compose-file docker-compose.yml goapp
          echo "Deploying to Docker Swarm..."
          ssh ${{ env.USER }}@<MANAGER_NODE_IP> "docker stack deploy --compose-file docker-compose.yml goapp" # Replace with your actual command
