name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          path: .

      - name: List workspace contents (with tree)
        run: |
          echo "Workspace contents:"
          if command -v tree >/dev/null 2>&1; then
            tree $GITHUB_WORKSPACE
          else
            ls -l $GITHUB_WORKSPACE
          fi

      - name: Copy application files to server
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p /home/ubuntu/actions-runner/_work/server/server
          cp -r goapp /home/ubuntu/actions-runner/_work/server/server
          cp -r traefik /home/ubuntu/actions-runner/_work/server/server

      - name: Deploy Traefik (if not already deployed)
        run: |
          cd /home/ubuntu/actions-runner/_work/server/server/traefik && \
          docker stack deploy -c docker-compose.yml traefik
      - name: Deploy Go Application
        run: |
          cd /home/ubuntu/actions-runner/_work/server/server/goapp && \
          docker stack deploy -c docker-compose.yml goapp
