name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # Include this if you have submodules

      - name: List workspace contents
        run: |
          echo "Workspace contents:"
          ls -R $GITHUB_WORKSPACE  # List all files and directories recursively

      - name: Copy application files to server
        run: |
          echo "Copying application files to the server..."
          mkdir -p /home/ubuntu/server
          cp -r /home/ubuntu/server /home/ubuntu/actions-runner/_work/server/server


      - name: Deploy Traefik (if not already deployed)
        run: |
          echo "Deploying Traefik..."
          if ! docker stack ls | grep -q "traefik"; then
            cd /home/ubuntu/server/traefik && \
            docker stack deploy -c docker-compose.yml traefik
          else
            echo "Traefik is already deployed."
          fi

      - name: Deploy Go Application
        run: |
          echo "Deploying Go Application..."
          cd /home/ubuntu/server/goapp && \
          docker stack deploy -c docker-compose.yml goapp
