name: Deploy Go Application (Without Docker Image)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set USER environment variable
        run: echo "USER=$(whoami)" >> $GITHUB_ENV

      - name: Set MANAGER_NODE_IP environment variable
        run: echo "MANAGER_NODE_IP=${{ secrets.MANAGER_NODE_IP }}" >> $GITHUB_ENV

      - name: Add SSH key to agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Go Application on Manager Node
        run: |
          echo "Building Go application on manager node..."
          ssh ${{ env.USER }}@${{ env.MANAGER_NODE_IP }} \
            "cd /home/ubuntu/actions-runner/_work/server/server/goapp && go build -o main ."

      - name: Copy docker-compose.yml to manager node
        run: |
          scp server/goapp/docker-compose.yml ${{ env.USER }}@${{ env.MANAGER_NODE_IP }}:/home/ubuntu/actions-runner/_work/server/server/goapp

      - name: Deploy Go Application
        run: |
          echo "Deploying Go Application..."
          ssh ${{ env.USER }}@${{ env.MANAGER_NODE_IP }} \
            "docker stack deploy -c /home/ubuntu/actions-runner/_work/server/server/goapp/docker-compose.yml goapp"
