name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          path: .

      - name: List workspace contents (with tree)
        run: |
          echo "Workspace contents:"
          if command -v tree >/dev/null 2>&1; then
            tree $GITHUB_WORKSPACE
          else
            ls -l $GITHUB_WORKSPACE
          fi

      - name: Copy application files to server
        run: |
          mkdir -p /home/ubuntu/server
          cp -r $GITHUB_WORKSPACE/server/goapp/home/ubuntu/server/
          cp -r $GITHUB_WORKSPACE/server/traefik/home/ubuntu/server/

      - name: Deploy Traefik (if not already deployed)
        run: |
          if ! docker stack ls | grep -q "traefik"; then
            cd /home/ubuntu/server/traefik && \
            docker stack deploy -c docker-compose.yml traefik
          fi

      - name: Deploy Go Application
        run: |
          cd /home/ubuntu/server/goapp && \
          docker stack deploy -c docker-compose.yml goapp
