name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List workspace contents
        run: |
          echo "Workspace contents:"
          ls

      - name: Copy application files to server
        run: |
          mkdir -p /home/ubuntu/server
          rsync -av --exclude '.git' ./ /home/ubuntu/server/


      - name: Update application
        run: |
          cd /home/ubuntu/server/goapp && \
          docker-compose pull && \
          docker-compose up -d
