name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List workspace contents
        run: |
          echo "Workspace contents:"
          ls

      - name: Copy application files to server
        run: |
          mkdir -p /home/ubuntu/server
          cp -r cp -r /server /home/ubuntu/server/

      - name: Deploy Traefik (if not already deployed)
        run: |
          if ! docker stack ls | grep -q "traefik"; then
            cd /home/ubuntu/server/traefik && \
            docker stack deploy -c docker-compose.yml traefik
          fi

      - name: Deploy Go Application
        run: |
          cd /home/ubuntu/server/goapp && \
          docker stack deploy -c docker-compose.yml goapp
